name = "orographic"
compatibility_date = "2026-04-01"
pages_build_output_dir = "./web"

[[d1_databases]]
binding = "POSITIONS_DB"
database_name = "orographic-position-history"
database_id = "b3bec1cd-35ef-40d5-b89d-17ac455c614c"

[ai]
binding = "AI"
