"""
engine/backtest/replay.py

Replays the Scout → Forge pipeline for a given historical Monday
using Black-Scholes pricing + historical equity data.

Council is NOT replayed here by default — we backtest ALL Forge candidates
so we measure what the full candidate pool would have returned.

Signal generation now shares the same ML model path as the live scout,
ensuring backtest and live results are generated by the same scorer.
Falls back to the heuristic linear formula when the model is absent.
"""
from __future__ import annotations

import logging
import warnings
from dataclasses import dataclass
from datetime import date
from math import erf, exp, log as math_log, sqrt
from typing import Any

import numpy as np
import pandas as pd

from engine.orographic.schemas import ContractCandidate, MarketRegime, ScoutSignal
from engine.orographic.forge import (
    _breakeven_move_pct,
    _candidate_moneyness,
    _find_short_leg,
    _intrinsic,
    _long_leg_cap,
    _net_debit_cap,
    _projected_move_pct,
    _spread_cap,
)
from engine.orographic.scout import (
    _extract_features,
    _ml_scout_score,
    _heuristic_scout_score,
    _rsi,
    _atr_pct,
    _clip,
    _load_model,
)
from engine.orographic.market_data import compute_iv_rank, fetch_risk_free_rate
from engine.backtest.fetcher import (
    fetch_equity_history,
    friday_of_week,
    get_price_on,
    realized_vol_as_of,
)
from engine.backtest.options_provider import HistoricalOptionsProvider

log = logging.getLogger(__name__)


# ── Column flattening helper ─────────────────────────────────────────────────


def _flatten_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Flatten MultiIndex columns returned by recent yfinance versions."""
    if isinstance(df.columns, pd.MultiIndex):
        df = df.copy()
        df.columns = [col[0] if isinstance(col, tuple) else col for col in df.columns]
    return df


def _numeric_series(frame: pd.DataFrame, *names: str, fill_value: float | None = None) -> pd.Series:
    for name in names:
        if name in frame.columns:
            series = pd.to_numeric(frame[name], errors="coerce")
            return series.fillna(fill_value) if fill_value is not None else series
    series = pd.Series(index=frame.index, dtype=float)
    return series.fillna(fill_value) if fill_value is not None else series


def historical_corr_matrix_as_of(
    symbols: list[str],
    equity_histories: dict[str, pd.DataFrame],
    as_of: date,
    lookback_days: int = 60,
) -> np.ndarray | None:
    """
    Build a historical correlation matrix using only prices available on `as_of`.
    This keeps replay-time Council selection from peeking at current correlations.
    """
    unique = list(dict.fromkeys(symbols))
    if len(unique) < 2:
        return None

    rets: list[pd.Series] = []
    for sym in unique:
        hist = equity_histories.get(sym)
        if hist is None:
            return None
        frame = _flatten_columns(hist)
        mask = frame.index.date <= as_of
        close = pd.to_numeric(frame.loc[mask, "Close"], errors="coerce").dropna()
        if len(close) < 20:
            return None
        rets.append(close.pct_change().dropna().tail(lookback_days).rename(sym))

    combined = pd.concat(rets, axis=1).dropna()
    if combined.shape[1] != len(unique) or len(combined) < 10:
        return None
    return combined.corr().values


def build_signal_as_of(
    symbol: str,
    as_of: date,
    history_df: pd.DataFrame,
    regime: MarketRegime,
    spy_history: pd.DataFrame | None = None,
) -> ScoutSignal | None:
    """
    Run Scout signal generation against historical data ending on `as_of`.
    Uses the same ML model path as the live scout for backtest parity.
    """
    history_df = _flatten_columns(history_df)
    mask = history_df.index.date <= as_of
    frame = history_df[mask].copy()
    close = pd.to_numeric(frame["Close"], errors="coerce").dropna()
    if len(close) < 62:
        return None

    spot = float(close.iloc[-1])
    momentum_5d      = float(spot / close.iloc[-6]  - 1.0)
    momentum_20d     = float(spot / close.iloc[-21] - 1.0)
    realized_vol_20d = float(close.pct_change().rolling(20).std().iloc[-1] * (252 ** 0.5))
    rsi_14           = _rsi(close, period=14)
    atr_pct_14d      = _atr_pct(frame, period=14)

    # SPY context for ML features (slice to as_of)
    spy_close_aligned = None
    if spy_history is not None:
        spy_hist = _flatten_columns(spy_history)
        spy_mask = spy_hist.index.date <= as_of
        spy_slice = spy_hist[spy_mask]
        if len(spy_slice) >= 21:
            spy_close_aligned = pd.to_numeric(spy_slice["Close"], errors="coerce").dropna()
            spy_close_aligned = spy_close_aligned.reindex(close.index, method="ffill").dropna()

    # ── ML inference (Sanitized & Unbiased) ──
    # We are now using a model trained strictly on pre-2026 data.
    feats    = _extract_features(close, frame, spy_close_aligned)
    ml_score = _ml_scout_score(feats)
    using_ml = ml_score is not None
    
    if using_ml:
        raw_score       = ml_score
        technical_score = raw_score
        empirical_score = 0.0
        direction       = "call" if raw_score >= 0 else "put"
    else:
        # Heuristic fallback (if model loading fails)
        technical_score, empirical_score, _ = _heuristic_scout_score(
            momentum_5d, momentum_20d, rsi_14, realized_vol_20d,
            atr_pct_14d, z_score=0.0, regime_bonus=0.0,
        )
        direction = "call" if technical_score >= 0 else "put"
        raw_score = None

    # Hard regime veto (same as live path)
    if regime.mode == "risk_on"  and direction == "put":  return None
    if regime.mode == "risk_off" and direction == "call": return None

    regime_bonus = 0.0
    if   regime.mode == "risk_on"  and direction == "call": regime_bonus =  0.08
    elif regime.mode == "risk_off" and direction == "put":  regime_bonus =  0.08
    elif regime.mode != "neutral":                          regime_bonus = -0.08

    if using_ml:
        scout_score = _clip(raw_score + regime_bonus)
    else:
        _, _, scout_score = _heuristic_scout_score(
            momentum_5d, momentum_20d, rsi_14, realized_vol_20d,
            atr_pct_14d, z_score=0.0, regime_bonus=regime_bonus,
        )

    notes: list[str] = []
    if using_ml:
        notes.append(f"ML model active (prob_bull={raw_score/2+0.5:.2%})")
    else:
        notes.append("heuristic fallback (model not found)")
    if abs(momentum_5d) > 0.035:
        notes.append("short-term momentum is strong")
    if 40.0 <= rsi_14 <= 60.0:
        notes.append("RSI is balanced")
    if atr_pct_14d > 0.05:
        notes.append("ATR elevated")

    return ScoutSignal(
        symbol=symbol,
        direction=direction,
        spot=round(spot, 4),
        momentum_5d=round(momentum_5d, 4),
        momentum_20d=round(momentum_20d, 4),
        rsi_14=round(rsi_14, 2),
        realized_vol_20d=round(realized_vol_20d, 4),
        atr_pct_14d=round(atr_pct_14d, 4),
        technical_score=round(technical_score, 4),
        empirical_score=round(empirical_score, 4),
        scout_score=round(scout_score, 4),
        notes=notes,
    )


def infer_regime_as_of(
    spy_history: pd.DataFrame,
    vix_history: pd.DataFrame,
    as_of: date,
) -> MarketRegime:
    """Reconstruct the market regime as it would have been computed on `as_of`."""
    spy_history = _flatten_columns(spy_history)
    vix_history = _flatten_columns(vix_history)
    spy_mask = spy_history.index.date <= as_of
    vix_mask = vix_history.index.date <= as_of
    spy_close = pd.to_numeric(spy_history[spy_mask]["Close"], errors="coerce").dropna()
    vix_close = pd.to_numeric(vix_history[vix_mask]["Close"], errors="coerce").dropna()

    if len(spy_close) < 21 or len(vix_close) < 6:
        return MarketRegime(mode="neutral", bias=0.0, source_symbol="SPY")

    spy_5 = float(spy_close.iloc[-1] / spy_close.iloc[-6] - 1.0)
    spy_20 = float(spy_close.iloc[-1] / spy_close.iloc[-21] - 1.0)
    vix_level = float(vix_close.iloc[-1])
    vix_5 = float(vix_close.iloc[-1] / vix_close.iloc[-6] - 1.0)

    def clip1(v: float) -> float:
        return max(-1.0, min(1.0, v))

    bias = clip1((spy_5 * 6.0) + (spy_20 * 4.0) - (vix_5 * 0.8) - ((vix_level - 20.0) / 35.0))
    if bias >= 0.18:
        mode = "risk_on"
    elif bias <= -0.18:
        mode = "risk_off"
    else:
        mode = "neutral"
    return MarketRegime(mode=mode, bias=round(bias, 4), source_symbol="SPY")


def forge_candidates_as_of(
    signal: ScoutSignal,
    as_of: date,
    options_provider: HistoricalOptionsProvider,
    *,
    min_abs_delta: float = 0.25,
    max_abs_delta: float = 0.75,
    max_premium: float = 4.50,
) -> list[ContractCandidate]:
    """
    Generate ContractCandidate objects using real historical chains.
    Reconstructs a live-like Forge pass against historical option chains,
    including spread-aware debit selection and feasibility filters.
    """
    candidates: list[ContractCandidate] = []
    expiry = friday_of_week(as_of)
    spot = signal.spot
    direction = signal.option_type if hasattr(signal, "option_type") else signal.direction
    risk_free_rate = fetch_risk_free_rate()
    net_debit_cap = _net_debit_cap(spot, max_premium)
    long_leg_cap = _long_leg_cap(net_debit_cap)
    effective_spread_cap = _spread_cap(spot, 0.18)
    projected_move = _projected_move_pct(signal, MarketRegime(mode="neutral", bias=0.0, source_symbol="SPY"))
    projected_spot = spot * (1 + projected_move) if direction == "call" else spot * (1 - projected_move)
    days_to_expiry = max((expiry - as_of).days, 1)
    time_to_expiry_years = max(days_to_expiry / 365.0, 1.0 / 365.0)

    chain = options_provider.get_chain(signal.symbol, as_of, fallback_spot=spot, fallback_vol=signal.realized_vol_20d or 0.35)
    if chain.empty:
        return []

    # Filter to only the correct option type & expiry matching the same week
    opt_type_char = 'C' if direction == "call" else 'P'
    valid_opts = chain[
        (chain["option_type"] == opt_type_char) &
        (pd.to_datetime(chain["expire_date"]).dt.date == expiry)
    ].copy()
    if valid_opts.empty:
        return []

    valid_opts["bid"] = _numeric_series(valid_opts, "bid")
    valid_opts["ask"] = _numeric_series(valid_opts, "ask")
    valid_opts["strike"] = _numeric_series(valid_opts, "strike")
    valid_opts["delta"] = _numeric_series(valid_opts, "delta")
    valid_opts["impliedVolatility"] = _numeric_series(
        valid_opts,
        "implied_volatility",
        "impliedVolatility",
        fill_value=signal.realized_vol_20d or 0.35,
    )
    valid_opts["open_interest"] = _numeric_series(
        valid_opts,
        "open_interest",
        "openInterest",
        fill_value=500,
    )
    valid_opts["trade_volume"] = _numeric_series(
        valid_opts,
        "trade_volume",
        "volume",
        fill_value=100,
    )
    valid_opts = valid_opts.dropna(subset=["bid", "ask", "strike"]).copy()
    valid_opts = valid_opts[(valid_opts["bid"] > 0) & (valid_opts["ask"] > 0)].copy()
    if valid_opts.empty:
        return []

    short_pool = valid_opts.copy()
    valid_opts = valid_opts[valid_opts["ask"] <= long_leg_cap].copy()
    if valid_opts.empty:
        return []

    mid = (valid_opts["bid"] + valid_opts["ask"]) / 2.0
    valid_opts = valid_opts[mid > 0].copy()
    valid_opts["spread_pct"] = (valid_opts["ask"] - valid_opts["bid"]) / ((valid_opts["bid"] + valid_opts["ask"]) / 2.0)
    valid_opts = valid_opts[valid_opts["spread_pct"] <= effective_spread_cap].copy()
    if valid_opts.empty:
        return []

    valid_opts = valid_opts[
        (valid_opts["open_interest"] >= 150)
        & (valid_opts["trade_volume"] >= 25)
    ].copy()
    if valid_opts.empty:
        return []

    valid_opts["moneyness"] = valid_opts["strike"].apply(
        lambda strike: _candidate_moneyness(direction, spot, float(strike))
    )
    valid_opts = valid_opts[(valid_opts["moneyness"] >= -0.05) & (valid_opts["moneyness"] <= 0.03)].copy()
    if valid_opts.empty:
        return []

    valid_opts["delta"] = valid_opts.apply(
        lambda row: float(row["delta"]) if pd.notna(row["delta"]) else black_scholes_delta(
            spot=spot,
            strike=float(row["strike"]),
            time_to_expiry_years=time_to_expiry_years,
            risk_free_rate=risk_free_rate,
            volatility=max(float(row["impliedVolatility"]), 0.10),
            option_type=direction,
        ),
        axis=1,
    )
    valid_opts = valid_opts[valid_opts["delta"].notna()].copy()
    valid_opts = valid_opts[valid_opts["delta"].abs().between(min_abs_delta, max_abs_delta)].copy()
    if valid_opts.empty:
        return []

    for _, row in valid_opts.iterrows():
        ask = float(row["ask"])
        bid = float(row["bid"])
        delta = float(row["delta"])
        vol = max(float(row["impliedVolatility"]), 0.10)
        strike = float(row["strike"])

        short_leg = _find_short_leg(
            short_pool,
            option_type=direction,
            long_strike=strike,
            long_delta=delta,
            spot=spot,
            time_to_expiry_years=time_to_expiry_years,
            risk_free_rate=risk_free_rate,
            max_spread_pct=effective_spread_cap,
        )

        is_spread = False
        actual_premium = ask
        if short_leg is not None:
            spread_debit = ask - short_leg["bid"]
            if 0.05 < spread_debit <= net_debit_cap:
                is_spread = True
                actual_premium = spread_debit
        if not is_spread and ask > net_debit_cap:
            continue

        projected_value = _intrinsic(direction, projected_spot, strike)
        intrinsic_now = _intrinsic(direction, spot, strike)
        if is_spread and short_leg is not None:
            projected_value = max(
                projected_value - _intrinsic(direction, projected_spot, short_leg["strike"]),
                0.0,
            )
            intrinsic_now = max(
                intrinsic_now - _intrinsic(direction, spot, short_leg["strike"]),
                0.0,
            )

        spread_pct = float(row["spread_pct"])
        expected_return_pct = projected_value / actual_premium - 1.0
        breakeven_move = _breakeven_move_pct(direction, spot, strike, actual_premium)
        extrinsic_ratio = max(actual_premium - intrinsic_now, 0.0) / actual_premium if actual_premium > 0 else 1.0
        allocation_weight = round(min(max(0.35 / vol, 0.25), 3.0), 4)
        ivr = compute_iv_rank(signal.symbol, vol)
        ivr_penalty = max(ivr - 0.70, 0.0) * 0.4
        vrp_penalty = max(vol - signal.realized_vol_20d - 0.10, 0.0) * 2.0
        liquidity_score = max(0.0, min(1.0,
            0.45
            + 0.18 * min(float(row["open_interest"]) / 800.0, 1.0)
            + 0.18 * min(float(row["trade_volume"]) / 300.0, 1.0)
            - 0.35 * min(spread_pct / effective_spread_cap, 1.0)
        ))
        economics_score = max(0.0, min(1.0,
            0.50
            + 0.25 * min(expected_return_pct / 1.5, 1.0)
            + 0.15 * min((projected_move - breakeven_move) / 0.05, 1.0)
            + 0.10 * (1.0 - min(extrinsic_ratio, 1.0))
            - 0.15 * max(extrinsic_ratio - 0.90, 0.0) / 0.10
            - vrp_penalty
            - ivr_penalty
        ))
        forge_score = max(0.0, min(1.0,
            0.45 * ((signal.scout_score + 1.0) / 2.0)
            + 0.30 * liquidity_score
            + 0.25 * economics_score
        ))

        contract_symbol = str(row.get("contractSymbol", "")) or f"{signal.symbol}{expiry.strftime('%y%m%d')}{opt_type_char}{int(strike * 1000):08d}"
        notes = ["Sourced via OptionsDX Loader"]
        if is_spread and short_leg is not None:
            notes.append(
                f"debit spread selected: {strike:.2f}/{short_leg['strike']:.2f} for premium control"
            )

        candidates.append(ContractCandidate(
            symbol=signal.symbol,
            contract_symbol=contract_symbol,
            option_type=direction,
            expiry=expiry.isoformat(),
            strike=strike,
            bid=bid,
            ask=ask,
            last=round((bid + ask) / 2.0, 4),
            premium=ask,
            contract_cost=round(actual_premium * 100.0, 2),
            spread_pct=round(spread_pct, 4),
            open_interest=int(float(row["open_interest"])),
            volume=int(float(row["trade_volume"])),
            implied_volatility=round(vol, 4),
            delta=round(delta, 4),
            moneyness=round(float(row["moneyness"]), 4),
            projected_move_pct=round(projected_move, 4),
            breakeven_move_pct=round(breakeven_move, 4),
            expected_return_pct=round(expected_return_pct, 4),
            extrinsic_ratio=round(extrinsic_ratio, 4),
            scout_score=signal.scout_score,
            forge_score=round(forge_score, 4),
            short_strike=round(short_leg["strike"], 4) if short_leg else None,
            short_ask=round(short_leg["ask"], 4) if short_leg else None,
            short_bid=round(short_leg["bid"], 4) if short_leg else None,
            is_spread=is_spread,
            spread_cost=round(actual_premium, 4),
            allocation_weight=allocation_weight,
            iv_rank=round(ivr, 4),
            notes=notes,
        ))

    candidates.sort(key=lambda c: c.forge_score, reverse=True)
    return candidates

@dataclass
class WeekReplay:
    """The signals and candidates reconstructed for a given Monday."""
    monday: date
    friday: date
    regime: MarketRegime
    signals: list[ScoutSignal]
    candidates: list[ContractCandidate]


def replay_week(
    monday: date,
    symbols: list[str],
    equity_histories: dict[str, pd.DataFrame],
    spy_history: pd.DataFrame,
    vix_history: pd.DataFrame,
    options_provider: HistoricalOptionsProvider,
) -> WeekReplay:
    """
    Reconstruct what Scout + Forge would have produced on the given Monday.
    `equity_histories` maps symbol → DataFrame (already fetched and cached).
    """
    regime = infer_regime_as_of(spy_history, vix_history, monday)

    signals: list[ScoutSignal] = []
    for symbol in symbols:
        hist = equity_histories.get(symbol)
        if hist is None:
            continue
        try:
            sig = build_signal_as_of(symbol, monday, hist, regime, spy_history)
        except Exception as exc:
            log.warning("Scout replay failed for %s on %s: %s", symbol, monday, exc)
            sig = None
        if sig is not None:
            signals.append(sig)

    signals.sort(key=lambda s: abs(s.scout_score), reverse=True)

    candidates: list[ContractCandidate] = []
    for sig in signals:
        try:
            cands = forge_candidates_as_of(sig, monday, options_provider)
        except Exception as exc:
            log.warning("Forge replay failed for %s on %s: %s", sig.symbol, monday, exc)
            cands = []
        candidates.extend(cands)

    candidates.sort(key=lambda c: c.forge_score, reverse=True)

    return WeekReplay(
        monday=monday,
        friday=friday_of_week(monday),
        regime=regime,
        signals=signals,
        candidates=candidates,
    )
